const { defineConfig } = require('eslint/config');
const reactCompiler = require('eslint-plugin-react-compiler');
const tsParser = require('@typescript-eslint/parser');
const holidai = require('./tools/eslint');

module.exports = defineConfig([
  {
    ...reactCompiler.configs.recommended,
    files: ['**/*.{js,jsx,ts,tsx}'],
    languageOptions: {
      parser: tsParser,
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: tsParser,
    },
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'react-native',
              importNames: ['ActivityIndicator'],
              message:
                'Do not use `ActivityIndicator`. Use `CustomSpinner` from features/core/design-system — the app has exactly one spinner.',
            },
          ],
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: 'TSEnumDeclaration',
          message: 'Do not use `enum`. Use a `const` object with `as const` instead (see wiki/docs/ARCHITECTURE.md).',
        },
        {
          selector: 'TSAsExpression[typeAnnotation.typeName.name="Error"]',
          message:
            'Do not cast `as Error`. Use `ensureError()` from features/core/error (see wiki/docs/ERROR_HANDLING.md).',
        },
      ],
    },
  },
  {
    // ViewModel contract rules — see tools/eslint and wiki/docs/ARCHITECTURE.md (ui/ — The
    // ViewModel contract). Rolled out at `warn` (issue #403), then enforced as `error` once every
    // feature's ViewModels were migrated (issue #404). A violation is now unmergeable.
    files: ['**/*.logic.ts'],
    plugins: { holidai },
    rules: {
      'holidai/viewmodel-return-shape': 'error',
    },
  },
  {
    files: ['**/*.tsx'],
    plugins: { holidai },
    rules: {
      'holidai/prefer-viewmodel': 'error',
    },
  },
  {
    // tools/ is build-time tooling (like scripts/) — not linted with app rules.
    ignores: [
      'dist/*',
      'convex/_generated/*',
      '.claude/workflows/**',
      'tools/**',
      // Regenerated by the Metro plugin on every Storybook start; gitignored.
      '.rnstorybook/storybook.requires.ts',
    ],
  },
]);
