export const IMAGES_TYPES = {
  UnsplashApiKey: Symbol.for('Images.UnsplashApiKey'),
  GooglePlacesApiKey: Symbol.for('Images.GooglePlacesApiKey'),
  UnsplashImageRepository: Symbol.for('Images.UnsplashImageRepository'),
  GooglePlacesImageRepository: Symbol.for('Images.GooglePlacesImageRepository'),
  GooglePlacesImageListRepository: Symbol.for('Images.GooglePlacesImageListRepository'),
  GooglePlacesPhotoNamesRepository: Symbol.for('Images.GooglePlacesPhotoNamesRepository'),
  FetchUnsplashImageUseCase: Symbol.for('Images.FetchUnsplashImageUseCase'),
  FetchGooglePlaceImageUseCase: Symbol.for('Images.FetchGooglePlaceImageUseCase'),
  FetchGooglePlaceImagesUseCase: Symbol.for('Images.FetchGooglePlaceImagesUseCase'),
  WikimediaDishImageRepository: Symbol.for('Images.WikimediaDishImageRepository'),
  FetchWikimediaDishImageUseCase: Symbol.for('Images.FetchWikimediaDishImageUseCase'),
  BuildPlacePhotoUrlUseCase: Symbol.for('Images.BuildPlacePhotoUrlUseCase'),
  FetchPhotoNamesUseCase: Symbol.for('Images.FetchPhotoNamesUseCase'),
} as const;
