export const colors = {
  alpha: '#220059',
  primary: '#A01A7D',
  primaryLight: '#C41E95',
  primaryDisabled: '#E5B3D1',
  primaryBlack: '#000000',
  primaryBlackDisabled: '#8E8E8F',
  primaryWhite: '#FFFFFF',
  primaryWhiteDisabled: '#F9F9F9',
  primaryGrey: '#8E8E8F',
  secondaryGrey: '#f5f5f5',
  primaryYellow: '#FFE5D9',
  secondaryYellow: '#FFD9B3',
  primaryGreen: '#D8E2DC',
  primaryPink: '#FFCAD4',
  secondaryPink: '#F4ACB7',
  primaryBlue: '#4361EE',
  secondaryBlue: '#96d0ff',
  tertiaryBlue: '#63b3ff',
  primaryRed: '#FFD9D9',
  secondaryGreen: '#8AFF8A',
  tertiaryGreen: '#57C17B',
} as const;
