import type { Ionicons } from '@expo/vector-icons';

export const icons: Record<string, keyof typeof Ionicons.glyphMap> = {
  close: 'close',
  location: 'location',
  locationOutline: 'location-outline',
  globeOutline: 'globe-outline',
  personCircleOutline: 'person-circle-outline',
  arrowBack: 'arrow-back',
  arrowRight: 'chevron-forward',
  addCircle: 'add-circle',
  add: 'add',
  remove: 'trash',
  hearth: 'heart-outline',
  heartOutline: 'heart-sharp',
  success: 'checkmark-circle-sharp',
  list: 'list-circle-sharp',
  calendar: 'calendar-number-outline',
  calendarOutline: 'calendar-outline',
  cash: 'cash-outline',
  people: 'people-outline',
  airplane: 'airplane-sharp',
  boat: 'boat',
  home: 'home',
  diamond: 'diamond-outline',
  bag: 'bag',
  card: 'card-outline',
  language: 'language-outline',
  delete: 'trash-outline',
  logout: 'log-out-outline',
  bus: 'bus-outline',
  clock: 'time-outline',
  star: 'star',
};
